### ISSUE TITLE
Relay plugin failing when running multiple jest tests in parallel

### ISSUE THREAD

**Issue by kaelig** [swc-project/plugins#177]
Here are versions of swc and plugins I use:

```
    "@swc/core": "1.3.52",
    "@swc/jest": "0.2.26",
    "@swc/plugin-relay": "1.5.59",
    "jest_workaround": "0.75.4",
```

Unless I run tests one by one (with `--runInBand`), I keep getting errors like this one:

```
 FAIL  functions/access-control/access-control-utils.spec.ts
  ● Test suite failed to run

    failed to handle: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

      at Compiler.transformSync (node_modules/@swc/core/index.js:241:29)
      at transformSync (node_modules/@swc/core/index.js:348:21)
      at Object.process (node_modules/@swc/jest/index.js:73:45)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:542:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:671:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:723:19)
```

---

I broke down what happens based on CLI options I pass to Jest.

### No options (using defaults) 🤒 

```
Test Suites: 364 failed, 1 skipped, 54 passed, 418 of 419 total
Tests:       2 skipped, 359 passed, 361 total
Snapshots:   5 passed, 5 total
Time:        17.521 s, estimated 28 s
```

### `--maxWorkers=2 --maxConcurrency=1` 😵‍💫 

```
Test Suites: 364 failed, 1 skipped, 54 passed, 418 of 419 total
Tests:       2 skipped, 359 passed, 361 total
Snapshots:   5 passed, 5 total
Time:        44.874 s
```

### `--runInBand` ✅ 

```
Test Suites: 0 failed, 1 skipped, 418 passed, 418 of 419 total
Tests:       0 failed, 3 skipped, 3351 passed, 3351 total
Snapshots:   9 passed, 9 total
Time:        251.08 s
```

#### Run 1 😢 

```
yarn test src/actions/accountMembers.spec.ts
yarn run v1.22.19
$ cross-env NODE_ENV=test TZ=UTC jest src/actions/accountMembers.spec.ts

 RUNS  src/actions/accountMembers.spec.ts
thread '<unnamed>' panicked at 'assertion failed: prev.start > max', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-co FAIL  src/actions/accountMembers.spec.ts_info.rs:224:9
  ● Test suite failed to run

    failed to handle: assertion failed: prev.start > max

      4 |
      5 | import { selectMembers } from './accountMembers';
    > 6 |
        | ^
      7 | describe('Returns the sorted account members list', () => {
      8 |   const store = {
      9 |     accountMembers: fromJS({

      at Compiler.transformSync (node_modules/@swc/core/index.js:241:29)
      at transformSync (node_modules/@swc/core/index.js:348:21)
      at Object.process (node_modules/@swc/jest/index.js:73:45)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:542:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:671:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:723:19)
      at Object.<anonymous> (src/actions/accountMembers.spec.ts:6:18)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.518 s
```

#### Run 2 🎉 

```
$ cross-env NODE_ENV=test TZ=UTC jest src/actions/accountMembers.spec.ts
 PASS  src/actions/accountMembers.spec.ts
  Returns the sorted account members list
    ✓ Invited team members (with role "Invited") are at the end of the list (1 ms)
    ✓ Team members are sorted by updated_at (most recent first) (1 ms)
    ✓ Invited team members (with role "Invited") are sorted by updated_at (most recent first)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        0.759 s
```

- I tried on an m1 mac and on an Ubuntu docker container – same results.
- I tried to reproduce in a small & fresh project with similar settings to the ones we have in our codebase, but couldn't :(

**Comment by kwonoj** [comment]
Hope to get some reproducible repo. Otherwise all of the fix would be a guesswork, cannot able to tell if it's fixed or not.

**Comment by kaelig** [comment]
This might be a little unorthodox, but would you be open to hop on a call so I can show you what's going on (in Netlify's codebase itself)? I'm not sure what part of our setup might be causing these failures, but you might immediately spot the culprit!

**Comment by kwonoj** [comment]
I wish I could do, but I don't think my full-time job allows to me to peek production codebase of other companies unless I go through legal approval & some other processes.

**Comment by kaelig** [comment]
Oh I assure you I'd only show you config files and non-sensitive code. No PII or sensitive data will show up on the screen!

**Comment by kdy1** [comment]
I think this is fixed. Can you try updating `@swc/core`?

**Comment by kdy1** [comment]
Closing as stale
