### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by coder-xiaotian** [swc-project/plugins#190]
I want to write an swc plugin to transform the mui component to the client component automatically. But now I have some problems.
I build my plugin using `cargo build-wasi --release`, then npm link to my next.js project.
My next.js project will get the blow compile error.
```
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/client/next-dev.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/client/router.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/pages/_app.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/pages/_error.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/client/app-next-dev.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
- error ./node_modules/next/dist/client/next-dev.js
Error: failed to process failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/client/next-dev.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable
- warn Fast Refresh had to perform a full reload due to a runtime error.
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/client/next-dev.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/client/next-dev.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/client/router.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/client/dev/amp-dev.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/client/dev/amp-dev.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/client/router.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/pages/_app.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/pages/_error.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/pages/_app.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/xiaotian/lazy-cut/node_modules/next/dist/pages/_error.js")'

Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/use_client.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.41/src/plugin.rs:162:14
- error Error: Cannot find module '/Users/xiaotian/lazy-cut/.next/fallback-build-manifest.json'
Require stack:
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/load-components.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/next-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/next.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/lib/render-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at /Users/xiaotian/lazy-cut/node_modules/next/dist/server/require-hook.js:189:36
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadDefaultErrorComponentsImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/load-components.js:40:24)
    at DevServer.getFallbackErrorComponents (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js:1283:73)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DevServer.renderErrorToResponseImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:1595:40)
    at async DevServer.pipeImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:641:25)
    at async Object.fn (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/next-server.js:1139:21)
    at async Router.execute (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/router.js:315:32)
    at async DevServer.runImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:615:29)
    at async DevServer.run (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js:897:20)
    at async DevServer.handleRequestImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:546:20) {
  digest: undefined
}
- error Error: Cannot find module '/Users/xiaotian/lazy-cut/.next/fallback-build-manifest.json'
Require stack:
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/load-components.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/next-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/next.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/lib/render-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at /Users/xiaotian/lazy-cut/node_modules/next/dist/server/require-hook.js:189:36
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadDefaultErrorComponentsImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/load-components.js:40:24)
    at DevServer.getFallbackErrorComponents (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js:1283:73)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DevServer.renderErrorToResponseImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:1595:40)
    at async DevServer.pipeImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:641:25)
    at async Object.fn (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/next-server.js:1139:21)
    at async Router.execute (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/router.js:315:32)
    at async DevServer.runImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:615:29)
    at async DevServer.run (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js:897:20)
    at async DevServer.handleRequestImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:546:20) {
  digest: undefined
}
Error: Cannot find module '/Users/xiaotian/lazy-cut/.next/fallback-build-manifest.json'
Require stack:
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/load-components.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/next-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/next.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/lib/render-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at /Users/xiaotian/lazy-cut/node_modules/next/dist/server/require-hook.js:189:36
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadDefaultErrorComponentsImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/load-components.js:40:24)
    at DevServer.getFallbackErrorComponents (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js:1283:73)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DevServer.renderErrorToResponseImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:1595:40)
    at async pipe.req.req (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:1461:30)
    at async DevServer.pipeImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:641:25)
    at async DevServer.run (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js:905:28)
    at async DevServer.handleRequestImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:546:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/server/load-components.js',
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/server/next-server.js',
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js',
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/server/next.js',
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/server/lib/render-server.js',
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/compiled/jest-worker/processChild.js'
  ]
}
Error: Cannot find module '/Users/xiaotian/lazy-cut/.next/fallback-build-manifest.json'
Require stack:
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/load-components.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/next-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/next.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/server/lib/render-server.js
- /Users/xiaotian/lazy-cut/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at /Users/xiaotian/lazy-cut/node_modules/next/dist/server/require-hook.js:189:36
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadDefaultErrorComponentsImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/load-components.js:40:24)
    at DevServer.getFallbackErrorComponents (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js:1283:73)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DevServer.renderErrorToResponseImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:1595:40)
    at async pipe.req.req (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:1461:30)
    at async DevServer.pipeImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:641:25)
    at async DevServer.run (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js:905:28)
    at async DevServer.handleRequestImpl (/Users/xiaotian/lazy-cut/node_modules/next/dist/server/base-server.js:546:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/server/load-components.js',
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/server/next-server.js',
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/server/dev/next-dev-server.js',
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/server/next.js',
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/server/lib/render-server.js',
    '/Users/xiaotian/lazy-cut/node_modules/next/dist/compiled/jest-worker/processChild.js'
  ]
}
```

I know this code to make the problem, but I don't know how to fix it.
```
let filepath = match data.get_context(&TransformPluginMetadataContextKind::Filename) {
    Some(s) => s,
    None => String::from("")
};
```
I hope someone can help me.

```[tasklist]
### Tasks
```

**Comment by coder-xiaotian** [comment]
This is my repository [https://github.com/coder-xiaotian/swc-useclient](https://github.com/coder-xiaotian/swc-useclient).

**Comment by coder-xiaotian** [comment]
I have find the answer.

[https://github.com/swc-project/swc/discussions/7619#discussioncomment-6358916](https://github.com/swc-project/swc/discussions/7619#discussioncomment-6358916)
