### ISSUE TITLE
Relay plugin fails to execute

### ISSUE THREAD

**Issue by dgreif** [swc-project/plugins#35]
First, huge thank you to @kwonoj for opening #33.  It's going to save GitHub a bunch of headaches trying to get both SWC and Relay running with Jest 😄.

We tried pulling it in today and got the following error when we ran `@swc/jest`:

```
failed to handle: failed to invoke plugin: failed to invoke `@swc/plugin-relay` as js transform plugin at node_modules/@swc/plugin-relay/swc_plugin_relay.wasm

    Caused by:
        0: RuntimeError: unreachable
               at __rust_start_panic (<module>[2529]:0xf0394)
               at rust_panic (<module>[2519]:0xf0058)
               at std::panicking::rust_panic_with_hook::h6f835c06e363bae7 (<module>[2518]:0xeffd5)
               at std::panicking::begin_panic_handler::{{closure}}::hde80e0a1ba88c211 (<module>[2501]:0xef202)
               at std::sys_common::backtrace::__rust_end_short_backtrace::hdcc677413d02e608 (<module>[2500]:0xef141)
               at rust_begin_unwind (<module>[2513]:0xef900)
               at core::panicking::panic_fmt::hfa8eb99d625b4b7c (<module>[2676]:0xfe7cb)
               at core::panicking::panic_display::h88368abab39fa36c (<module>[2705]:0xff936)
               at core::panicking::panic_str::h59cab0098c5f6827 (<module>[2694]:0xff59c)
               at core::option::expect_failed::h09b109351990dc60 (<module>[2693]:0xff56a)
               at __plugin_process_impl (<module>[444]:0x67cec)
               at __plugin_process_impl.command_export (<module>[2784]:0x103c4e)
        1: unreachable

      at std::panicking::rust_panic_with_hook::h6f835c06e363bae7 (<module>[2518]:0xeffd5)
      at std::panicking::begin_panic_handler::{{closure}}::hde80e0a1ba88c211 (<module>[2501]:0xef202)
      at std::sys_common::backtrace::__rust_end_short_backtrace::hdcc677413d02e608 (<module>[2500]:0xef141)
                 at rust_begin_unwind (<module>[2513]:0xef900)
      at core::panicking::panic_fmt::hfa8eb99d625b4b7c (<module>[2676]:0xfe7cb)
      at core::panicking::panic_display::h88368abab39fa36c (<module>[2705]:0xff936)
      at core::panicking::panic_str::h59cab0098c5f6827 (<module>[2694]:0xff59c)
      at core::option::expect_failed::h09b109351990dc60 (<module>[2693]:0xff56a)
                 at __plugin_process_impl (<module>[444]:0x67cec)
                 at __plugin_process_impl.command_export (<module>[2784]:0x103c4e)
          1: unreachable
      at Compiler.transformSync (node_modules/@swc/core/index.js:137:25)
      at transformSync (node_modules/@swc/core/index.js:217:21)
      at Object.process (node_modules/@swc/jest/index.js:55:45)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
```

Just as a sanity check, we tried a few other plugins, like `styled-components`, and they ran without issue.  Happy to provide any other info you may need, but I'm guessing this should be easy to reproduce if you pull the plugin into any other project.  Thanks again for adding this plugin!

**Comment by kwonoj** [comment]
with backtrace `core::option::expect_failed`, I assume this is probably some oversight while port over transform with plugin. Let me try quickly.

**Comment by kwonoj** [comment]
@dgreif OK, first, there were legit bugs need to be fixed. https://github.com/swc-project/plugins/pull/36 attempts to aim to amend it.

With this changes, you can try something similar to this:

```
const out = transformSync(code, {
  filename: 'input.tsx',
  jsc: {
    experimental: {
      plugins: [[
        '@swc/plugin-relay, {
          rootDir: __dirname,
          pagesDir: 'src/pages',
          src: 'src',
          artifactDirectory: './'
        }
      ]]
    }
  }
})
```

afaik `@swc/jest` passes some of args (like `filename`), expect that you have to supply some of configuration value to the plugin. It looks like this issue's panic comes from missing some of those values. 

```
interface RelayPluginConfig {
  rootDir: string;
  pagesDir: string;
  src: string;
  artifactDirectory: string;
  language: 'typescript' | 'flow'
}
```

This attempts to inherit next.js's relay config, but also requires few more cannot be inferred inside of plugin context.

I know this is not graceful interface, mostly due to I was in hurry to create plugin without lot of considerations. Hope to evolve (and add some documentation) over time once it's proven to work.

**Comment by dgreif** [comment]
Seems to be working well so far @kwonoj.  Thanks again for getting to this so quickly!

One note, I'm not sure the `pagesDir` option is necessary here. I could be wrong, but that seems like a NextJS specific feature.  Otherwise, everything makes sense!

**Comment by kwonoj** [comment]
> One note, I'm not sure the pagesDir option is necessary here

Yes, I wasn't sure too but ported just in case. Let me try to take it out. Glad to hear it works!
