### ISSUE TITLE
Jest tests fail to run when experimental.plugins (relay) are added

### ISSUE THREAD

**Issue by damassi** [swc-project/plugins#56]
When running `@swc/jest` on vanilla files things work great, but as soon as I try to configure `@swc/plugin-relay` i'm getting an error:

```
 RUNS  src/test.jest.tsx
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/cn/Sites/artsy/force/src/test.jest.tsx")'

Caused by:
 FAIL  src/test.jest.tsxType', crates/swc/src/plugin.rs:278:14
  ● Test suite failed to run

    failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/cn/Sites/artsy/force/src/test.jest.tsx")'

    Caused by:
        Incompatible Export Type

      at Compiler.transformSync (node_modules/@swc/core/index.js:222:29)
      at transformSync (node_modules/@swc/core/index.js:325:21)
      at Object.process (node_modules/@swc/jest/index.js:72:45)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:612:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:758:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:815:19)
```

Here's my jest.config file:

```js
module.exports = {
  // other config 
    transform: {
    "(ts|tsx|js|jsx)$": [
      "@swc/jest",
      {
        jsc: {
          experimental: {
            plugins: [
              [
                "@swc/plugin-relay",
                {
                  language: "typescript",
                  // rootDir: __dirname,
                  src: "./src",
                  artifactDirectory: "./src/__generated__",
                },
              ],
            ],
          },
          parser: {
            decorators: true,
            dynamicImport: true,
            syntax: "typescript",
            tsx: true,
          },
          transform: {
            react: {
              runtime: "automatic",
            },
          },
        },
      },
    ],
  },
}
```

The test file is basically empty:

```
// tests.jest.tsx
describe("foo", () => {
  it("works", () => {
    expect(true).toBe(true)
  })
})
```

Since there isn't much documentation on how to use plugins with SWC and no examples I'm not sure if its my issue configuring or just the newness of the software. 

Thanks!

**Comment by kdy1** [comment]
Currently you have to use `@swc/core@v1.2.217`.
Sorry for the inconvinience

**Comment by damassi** [comment]
It looks like that version isn't published: 

<img width="542" alt="Screen Shot 2022-07-25 at 12 00 36 AM" src="https://user-images.githubusercontent.com/236943/180717218-cf7c46b2-5f71-4729-9d1a-b654bd3faa17.png">

**Comment by kdy1** [comment]
Oh, you are right, please use `1.2.215` instead.

**Comment by damassi** [comment]
Will give this a try and report back tomorrow. Thanks for the quick response!

**Comment by damassi** [comment]
This change fixed the issue observed. Still running into other issues, but those are likely configuration related 👍

**Comment by huv1k** [comment]
I am having a similar problem.
![CleanShot 2022-09-27 at 10 33 08@2x](https://user-images.githubusercontent.com/5691926/192476013-b572aae6-83b4-4963-b6a5-3debce43eea8.png)
I was trying to follow 
`@swc` versions bellow:
```
"@swc/core": "1.2.215",
"@swc/jest": "0.2.22",
"@swc/plugin-relay": "1.3.0"
```

**Comment by kdy1** [comment]
@huv1k  Your `@swc/core` is too old
